In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../dados/vendas_brutas.csv", sep=";")
df.head()

,id_venda,data_venda,vendedor,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento
0,1,05/01/2025,Ana Souza,Notebook,Eletrônicos,São Paulo,SP,1,3500,Cartão de Crédito
1,2,08/01/2025,Carlos Lima,Mouse,Periféricos,Rio de Janeiro,RJ,2,80,Pix
2,3,15/01/2025,Ana Souza,Teclado,Periféricos,São Paulo,SP,1,150,Boleto
3,4,02/02/2025,Mariana Costa,Monitor,Eletrônicos,Belo Horizonte,MG,1,900,Cartão de Crédito
4,5,10/02/2025,João Pedro,Notebook,Eletrônicos,Curitiba,PR,1,3600,Pix

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         10 non-null     int64
 1   data_venda       10 non-null     str
 2   vendedor         10 non-null     str
 3   produto          10 non-null     str
 4   categoria        10 non-null     str
 5   cidade           10 non-null     str
 6   estado           10 non-null     str
 7   quantidade       10 non-null     int64
 8   preco_unitario   10 non-null     int64
 9   forma_pagamento  10 non-null     str
dtypes: int64(3), str(7)
memory usage: 932.0 bytes

In [5]:
df.isnull().sum()

id_venda           0
data_venda         0
vendedor           0
produto            0
categoria          0
cidade             0
estado             0
quantidade         0
preco_unitario     0
forma_pagamento    0
dtype: int64

In [7]:
df["data_venda"] = pd.to_datetime(
    df["data_venda"],
    dayfirst=True,
    errors="coerce"
)

df["ano"] = df["data_venda"].dt.year
df["mes"] = df["data_venda"].dt.month

meses_ptbr = {
    1: "Janeiro",
    2: "Fevereiro",
    3: "Março",
    4: "Abril",
    5: "Maio",
    6: "Junho",
    7: "Julho",
    8: "Agosto",
    9: "Setembro",
    10: "Outubro",
    11: "Novembro",
    12: "Dezembro"
}

df["nome_mes"] = df["mes"].map(meses_ptbr)

df.head()

,id_venda,data_venda,vendedor,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,ano,mes,nome_mes
0,1,2025-01-05,Ana Souza,Notebook,Eletrônicos,São Paulo,SP,1,3500,Cartão de Crédito,2025,1,Janeiro
1,2,2025-01-08,Carlos Lima,Mouse,Periféricos,Rio de Janeiro,RJ,2,80,Pix,2025,1,Janeiro
2,3,2025-01-15,Ana Souza,Teclado,Periféricos,São Paulo,SP,1,150,Boleto,2025,1,Janeiro
3,4,2025-02-02,Mariana Costa,Monitor,Eletrônicos,Belo Horizonte,MG,1,900,Cartão de Crédito,2025,2,Fevereiro
4,5,2025-02-10,João Pedro,Notebook,Eletrônicos,Curitiba,PR,1,3600,Pix,2025,2,Fevereiro

In [8]:
df["data_venda"].isnull().sum()

np.int64(0)

In [9]:
df["faturamento"] = df["quantidade"] * df["preco_unitario"]

df.head()

,id_venda,data_venda,vendedor,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,ano,mes,nome_mes,faturamento
0,1,2025-01-05,Ana Souza,Notebook,Eletrônicos,São Paulo,SP,1,3500,Cartão de Crédito,2025,1,Janeiro,3500
1,2,2025-01-08,Carlos Lima,Mouse,Periféricos,Rio de Janeiro,RJ,2,80,Pix,2025,1,Janeiro,160
2,3,2025-01-15,Ana Souza,Teclado,Periféricos,São Paulo,SP,1,150,Boleto,2025,1,Janeiro,150
3,4,2025-02-02,Mariana Costa,Monitor,Eletrônicos,Belo Horizonte,MG,1,900,Cartão de Crédito,2025,2,Fevereiro,900
4,5,2025-02-10,João Pedro,Notebook,Eletrônicos,Curitiba,PR,1,3600,Pix,2025,2,Fevereiro,3600

In [11]:
df["vendedor"] = df["vendedor"].str.title()
df["produto"] = df["produto"].str.title()
df["categoria"] = df["categoria"].str.title()
df["cidade"] = df["cidade"].str.title()
df["forma_pagamento"] = df["forma_pagamento"].str.title()

df.head()

,id_venda,data_venda,vendedor,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,ano,mes,nome_mes,faturamento
0,1,2025-01-05,Ana Souza,Notebook,Eletrônicos,São Paulo,SP,1,3500,Cartão De Crédito,2025,1,Janeiro,3500
1,2,2025-01-08,Carlos Lima,Mouse,Periféricos,Rio De Janeiro,RJ,2,80,Pix,2025,1,Janeiro,160
2,3,2025-01-15,Ana Souza,Teclado,Periféricos,São Paulo,SP,1,150,Boleto,2025,1,Janeiro,150
3,4,2025-02-02,Mariana Costa,Monitor,Eletrônicos,Belo Horizonte,MG,1,900,Cartão De Crédito,2025,2,Fevereiro,900
4,5,2025-02-10,João Pedro,Notebook,Eletrônicos,Curitiba,PR,1,3600,Pix,2025,2,Fevereiro,3600

In [12]:
df = df.drop_duplicates()

df.shape

(10, 14)

In [13]:
df.groupby("produto")["faturamento"].sum().sort_values(ascending=False)

produto
Notebook    10650
Monitor      2800
Mouse         460
Teclado       430
Headset       360
Name: faturamento, dtype: int64

In [14]:
df.to_csv("../dados/vendas_tratadas.csv", sep=";", index=False, encoding="utf-8-sig")

print("Arquivo vendas_tratadas.csv gerado com sucesso!")

Arquivo vendas_tratadas.csv gerado com sucesso!